"""add hltb playtime columns

Revision ID: ad299fb6ab07
Revises: fcbe933c3489
Create Date: 2026-04-09 14:03:02.603609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad299fb6ab07'
down_revision: Union[str, None] = 'fcbe933c3489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('hltb_main_hours', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('hltb_main_extra_hours', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('hltb_completionist_hours', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('hltb_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'hltb_synced_at')
    op.drop_column('games', 'hltb_completionist_hours')
    op.drop_column('games', 'hltb_main_extra_hours')
    op.drop_column('games', 'hltb_main_hours')
    # ### end Alembic commands ###
